# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/chonKhoi.ui'
#
# Created: Sun Oct 29 21:13:17 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_KhoiDiemMW(object):
    def setupUi(self, KhoiDiemMW):
        KhoiDiemMW.setObjectName("KhoiDiemMW")
        KhoiDiemMW.resize(873, 525)
        KhoiDiemMW.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(KhoiDiemMW)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_step = QtGui.QLabel(self.centralwidget)
        self.lb_step.setGeometry(QtCore.QRect(20, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_step.setFont(font)
        self.lb_step.setObjectName("lb_step")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 130, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_back = QtGui.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(20, 450, 91, 27))
        self.btn_back.setObjectName("btn_back")
        self.btn_save_continue = QtGui.QPushButton(self.centralwidget)
        self.btn_save_continue.setGeometry(QtCore.QRect(110, 450, 121, 27))
        self.btn_save_continue.setObjectName("btn_save_continue")
        # self.btn_skip = QtGui.QPushButton(self.centralwidget)
        # self.btn_skip.setGeometry(QtCore.QRect(230, 450, 121, 27))
        # self.btn_skip.setObjectName("btn_skip")
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lb_step_2 = QtGui.QLabel(self.centralwidget)
        self.lb_step_2.setGeometry(QtCore.QRect(20, 80, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lb_step_2.setFont(font)
        self.lb_step_2.setObjectName("lb_step_2")
        self.cb_khoi = QtGui.QComboBox(self.centralwidget)
        self.cb_khoi.setGeometry(QtCore.QRect(240, 80, 91, 24))
        self.cb_khoi.setObjectName("cb_khoi")
        self.btn_themKhoi = QtGui.QPushButton(self.centralwidget)
        self.btn_themKhoi.setGeometry(QtCore.QRect(340, 80, 89, 27))
        self.btn_themKhoi.setObjectName("btn_themKhoi")
        self.lv_khoi = QtGui.QListView(self.centralwidget)
        self.lv_khoi.setGeometry(QtCore.QRect(20, 160, 121, 231))
        self.lv_khoi.setObjectName("lv_khoi")
        self.btn_xoaKhoi = QtGui.QPushButton(self.centralwidget)
        self.btn_xoaKhoi.setGeometry(QtCore.QRect(18, 400, 121, 27))
        self.btn_xoaKhoi.setObjectName("btn_xoaKhoi")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(150, 160, 701, 231))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtGui.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 229))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtGui.QWidget(self.scrollArea)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gl_nhapDiem = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gl_nhapDiem.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gl_nhapDiem.setContentsMargins(0, 0, 0, 0)
        self.gl_nhapDiem.setObjectName("gl_nhapDiem")
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gl_nhapDiem.addWidget(self.label_3, 0, 0, 1, 1)
        self.lb_thiThu = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_thiThu.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_thiThu.setWordWrap(True)
        self.lb_thiThu.setObjectName("lb_thiThu")
        self.gl_nhapDiem.addWidget(self.lb_thiThu, 0, 6, 1, 1)
        self.lb_hk111 = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_hk111.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk111.setWordWrap(True)
        self.lb_hk111.setObjectName("lb_hk111")
        self.gl_nhapDiem.addWidget(self.lb_hk111, 0, 3, 1, 1)
        self.lb_hk211 = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_hk211.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk211.setWordWrap(True)
        self.lb_hk211.setObjectName("lb_hk211")
        self.gl_nhapDiem.addWidget(self.lb_hk211, 0, 4, 1, 1)
        self.lb_hk112 = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_hk112.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk112.setWordWrap(True)
        self.lb_hk112.setObjectName("lb_hk112")
        self.gl_nhapDiem.addWidget(self.lb_hk112, 0, 5, 1, 1)
        self.lb_thiHsg = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_thiHsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_thiHsg.setWordWrap(True)
        self.lb_thiHsg.setObjectName("lb_thiHsg")
        self.gl_nhapDiem.addWidget(self.lb_thiHsg, 0, 7, 1, 1)
        self.lb_hk110 = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_hk110.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk110.setWordWrap(True)
        self.lb_hk110.setObjectName("lb_hk110")
        self.gl_nhapDiem.addWidget(self.lb_hk110, 0, 1, 1, 1)
        self.lb_hk210 = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_hk210.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk210.setWordWrap(True)
        self.lb_hk210.setObjectName("lb_hk210")
        self.gl_nhapDiem.addWidget(self.lb_hk210, 0, 2, 1, 1)
        self.lb_cap_thi = QtGui.QLabel(self.gridLayoutWidget)
        self.lb_cap_thi.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cap_thi.setWordWrap(True)
        self.lb_cap_thi.setObjectName("lb_hk210")
        self.gl_nhapDiem.addWidget(self.lb_cap_thi, 0, 8, 1, 1)
        self.scrollArea.setWidget(self.gridLayoutWidget)
        KhoiDiemMW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(KhoiDiemMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        KhoiDiemMW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(KhoiDiemMW)
        self.statusbar.setObjectName("statusbar")
        KhoiDiemMW.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(KhoiDiemMW)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(KhoiDiemMW)
        QtCore.QMetaObject.connectSlotsByName(KhoiDiemMW)

    def retranslateUi(self, KhoiDiemMW):
        KhoiDiemMW.setWindowTitle(QtGui.QApplication.translate("KhoiDiemMW", "Hệ thống trợ giúp chọn ngành 2018", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_step.setText(QtGui.QApplication.translate("KhoiDiemMW", "Bước 1 of 8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("KhoiDiemMW", "Nhập điểm các môn thuộc khối thi:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_back.setText(QtGui.QApplication.translate("KhoiDiemMW", "Quay lại", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_continue.setText(QtGui.QApplication.translate("KhoiDiemMW", "Lưu và tiếp tục", None, QtGui.QApplication.UnicodeUTF8))
        # self.btn_skip.setText(QtGui.QApplication.translate("KhoiDiemMW", "Bỏ qua bước này", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("KhoiDiemMW", "Các khối đã chọn", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_step_2.setText(QtGui.QApplication.translate("KhoiDiemMW", "Chọn các khối bạn sẽ thi:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_themKhoi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Thêm khối", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_xoaKhoi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Chọn lại", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_thiThu.setText(QtGui.QApplication.translate("KhoiDiemMW", "Thi thử", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk111.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 1 lớp 11", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk211.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 2 lớp 11", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk112.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 1 lớp 12", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_thiHsg.setText(QtGui.QApplication.translate("KhoiDiemMW", "Thi HSG(nếu có)", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cap_thi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Cấp Thi HSG", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk110.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 1 lớp 10", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk210.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 2 lớp 10", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("KhoiDiemMW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("KhoiDiemMW", "Exit", None, QtGui.QApplication.UnicodeUTF8))

