# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/chonKhoi.ui'
#
# Created: Thu Nov  2 10:23:54 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_KhoiDiemMW(object):
    def setupUi(self, KhoiDiemMW):
        KhoiDiemMW.setObjectName("KhoiDiemMW")
        KhoiDiemMW.resize(873, 525)
        KhoiDiemMW.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(KhoiDiemMW)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_step = QtGui.QLabel(self.centralwidget)
        self.lb_step.setGeometry(QtCore.QRect(20, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_step.setFont(font)
        self.lb_step.setObjectName("lb_step")
        self.btn_back = QtGui.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(20, 450, 91, 27))
        self.btn_back.setObjectName("btn_back")
        self.btn_save_continue = QtGui.QPushButton(self.centralwidget)
        self.btn_save_continue.setGeometry(QtCore.QRect(110, 450, 121, 27))
        self.btn_save_continue.setObjectName("btn_save_continue")
        # self.btn_skip = QtGui.QPushButton(self.centralwidget)
        # self.btn_skip.setGeometry(QtCore.QRect(230, 450, 121, 27))
        # self.btn_skip.setObjectName("btn_skip")
        self.btn_xoaKhoi = QtGui.QPushButton(self.centralwidget)
        self.btn_xoaKhoi.setGeometry(QtCore.QRect(18, 400, 121, 27))
        self.btn_xoaKhoi.setObjectName("btn_xoaKhoi")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 90, 431, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gl_top = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gl_top.setContentsMargins(0, 0, 0, 0)
        self.gl_top.setHorizontalSpacing(3)
        self.gl_top.setVerticalSpacing(1)
        self.gl_top.setObjectName("gl_top")
        self.lb_chonKhoi = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lb_chonKhoi.setFont(font)
        self.lb_chonKhoi.setWordWrap(True)
        self.lb_chonKhoi.setObjectName("lb_chonKhoi")
        self.gl_top.addWidget(self.lb_chonKhoi, 0, 0, 1, 1)
        self.cb_khoi = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cb_khoi.setObjectName("cb_khoi")
        self.gl_top.addWidget(self.cb_khoi, 0, 1, 1, 1)
        self.btn_themKhoi = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btn_themKhoi.setObjectName("btn_themKhoi")
        self.gl_top.addWidget(self.btn_themKhoi, 0, 2, 1, 1)
        self.gl_top.setColumnStretch(0, 4)
        self.gl_top.setColumnStretch(1, 1)
        self.gl_top.setColumnStretch(2, 1)
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 140, 831, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gl_parent = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gl_parent.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gl_parent.setSpacing(2)
        self.gl_parent.setContentsMargins(0, 0, 0, 0)
        self.gl_parent.setObjectName("gl_parent")
        self.lv_khoi = QtGui.QListView(self.gridLayoutWidget)
        self.lv_khoi.setObjectName("lv_khoi")
        self.gl_parent.addWidget(self.lv_khoi, 1, 0, 1, 1)
        self.lb_khoiDaChon = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lb_khoiDaChon.setFont(font)
        self.lb_khoiDaChon.setWordWrap(True)
        self.lb_khoiDaChon.setObjectName("lb_khoiDaChon")
        self.gl_parent.addWidget(self.lb_khoiDaChon, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scroll_bangDiem = QtGui.QWidget()
        # self.scroll_bangDiem.setGeometry(QtCore.QRect(0, 0, 747, 207))
        # self.scroll_bangDiem.setObjectName("scroll_bangDiem")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.scrollArea)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 741, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gl_nhapDiem = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gl_nhapDiem.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gl_nhapDiem.setSpacing(6)
        self.gl_nhapDiem.setContentsMargins(0, 0, 0, 0)
        self.gl_nhapDiem.setObjectName("gl_nhapDiem")
        self.lb_thiThu = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_thiThu.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_thiThu.setWordWrap(True)
        self.lb_thiThu.setObjectName("lb_thiThu")
        self.gl_nhapDiem.addWidget(self.lb_thiThu, 0, 6, 1, 1)
        self.lb_hk111 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_hk111.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk111.setWordWrap(True)
        self.lb_hk111.setObjectName("lb_hk111")
        self.gl_nhapDiem.addWidget(self.lb_hk111, 0, 3, 1, 1)
        self.lb_hk211 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_hk211.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk211.setWordWrap(True)
        self.lb_hk211.setObjectName("lb_hk211")
        self.gl_nhapDiem.addWidget(self.lb_hk211, 0, 4, 1, 1)
        self.lb_hk112 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_hk112.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk112.setWordWrap(True)
        self.lb_hk112.setObjectName("lb_hk112")
        self.gl_nhapDiem.addWidget(self.lb_hk112, 0, 5, 1, 1)
        self.lb_thiHsg = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_thiHsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_thiHsg.setWordWrap(True)
        self.lb_thiHsg.setObjectName("lb_thiHsg")
        self.gl_nhapDiem.addWidget(self.lb_thiHsg, 0, 7, 1, 1)
        self.lb_hk110 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_hk110.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk110.setWordWrap(True)
        self.lb_hk110.setObjectName("lb_hk110")
        self.gl_nhapDiem.addWidget(self.lb_hk110, 0, 1, 1, 1)
        self.lb_hk210 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_hk210.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_hk210.setWordWrap(True)
        self.lb_hk210.setObjectName("lb_hk210")
        self.gl_nhapDiem.addWidget(self.lb_hk210, 0, 2, 1, 1)
        self.lb_n = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_n.setText("")
        self.lb_n.setObjectName("lb_n")
        self.gl_nhapDiem.addWidget(self.lb_n, 0, 0, 1, 1)
        self.lb_capThi = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lb_capThi.setObjectName("lb_capThi")
        self.gl_nhapDiem.addWidget(self.lb_capThi, 0, 8, 1, 1)
        self.gl_nhapDiem.setColumnStretch(0, 3)
        self.gl_nhapDiem.setColumnStretch(1, 2)
        self.gl_nhapDiem.setColumnStretch(2, 2)
        self.gl_nhapDiem.setColumnStretch(3, 2)
        self.gl_nhapDiem.setColumnStretch(4, 2)
        self.gl_nhapDiem.setColumnStretch(5, 2)
        self.gl_nhapDiem.setColumnStretch(6, 2)
        self.gl_nhapDiem.setColumnStretch(7, 2)
        self.gl_nhapDiem.setColumnStretch(8, 2)
        self.scrollArea.setWidget(self.gridLayoutWidget_3)
        self.gl_parent.addWidget(self.scrollArea, 1, 1, 1, 1)
        self.lb_nhapDiem = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lb_nhapDiem.setFont(font)
        self.lb_nhapDiem.setWordWrap(True)
        self.lb_nhapDiem.setObjectName("lb_nhapDiem")
        self.gl_parent.addWidget(self.lb_nhapDiem, 0, 1, 1, 1)
        self.gl_parent.setColumnStretch(0, 1)
        self.gl_parent.setColumnStretch(1, 11)
        KhoiDiemMW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(KhoiDiemMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        KhoiDiemMW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(KhoiDiemMW)
        self.statusbar.setObjectName("statusbar")
        KhoiDiemMW.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(KhoiDiemMW)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(KhoiDiemMW)
        QtCore.QMetaObject.connectSlotsByName(KhoiDiemMW)

    def retranslateUi(self, KhoiDiemMW):
        KhoiDiemMW.setWindowTitle(QtGui.QApplication.translate("KhoiDiemMW", "Hệ thống trợ giúp chọn ngành 2018", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_step.setText(QtGui.QApplication.translate("KhoiDiemMW", "Bước 1 của 8", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_back.setText(QtGui.QApplication.translate("KhoiDiemMW", "Quay lại", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_continue.setText(QtGui.QApplication.translate("KhoiDiemMW", "Lưu và tiếp tục", None, QtGui.QApplication.UnicodeUTF8))
        # self.btn_skip.setText(QtGui.QApplication.translate("KhoiDiemMW", "Bỏ qua bước này", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_xoaKhoi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Chọn lại", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_chonKhoi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Chọn các khối bạn sẽ thi:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_themKhoi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Thêm khối", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_khoiDaChon.setText(QtGui.QApplication.translate("KhoiDiemMW", "Các khối đã chọn", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_thiThu.setText(QtGui.QApplication.translate("KhoiDiemMW", "Thi thử", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk111.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 1 lớp 11", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk211.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 2 lớp 11", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk112.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 1 lớp 12", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_thiHsg.setText(QtGui.QApplication.translate("KhoiDiemMW", "Thi HSG(nếu có)", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk110.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 1 lớp 10", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_hk210.setText(QtGui.QApplication.translate("KhoiDiemMW", "Học kỳ 2 lớp 10", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_capThi.setText(QtGui.QApplication.translate("KhoiDiemMW", "Cấp Thi", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_nhapDiem.setText(QtGui.QApplication.translate("KhoiDiemMW", "Nhập điểm các môn thuộc khối thi:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("KhoiDiemMW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("KhoiDiemMW", "Exit", None, QtGui.QApplication.UnicodeUTF8))

